### PR TITLE
Initial working deployment

### PR DESCRIPTION
**Pull request by waxlamp**
@opadron please take a look.

To use it, clone this repository then run `vagrant up` in the top level. I am using Vagrant 1.9.2 and Ansible 2.2.1.0.

### CODE REVIEW

**Comment by waxlamp** [comment]
@opadron this is ready for a test/review.

**Comment by opadron** [comment]
I got this when trying on my macbook:

    `galaxy_role_file` does not exist on the host: /Users/opadron/tmp2/osumo-ansible/ansible/trusty64/requirements.yml

I'm guessing there's a role or some other that I need to install?

**Comment by waxlamp** [comment]
Oops looks like I forgot to include an important file. Please try again @opadron :cat:

**Comment by opadron** [comment]
LGTM

**Pull request merged**
